// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYBFy5w8y8FOToPqmtrEP7lh9ecxyI3p8',
    appId: '1:149009916741:web:3100ca7dcedb0d26a3542c',
    messagingSenderId: '149009916741',
    projectId: 'wefin-calculator',
    authDomain: 'wefin-calculator.firebaseapp.com',
    storageBucket: 'wefin-calculator.firebasestorage.app',
    measurementId: 'G-FV3R809BWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyNfuzxjbYFFaiVugMTHMLdYwiWhwMvzY',
    appId: '1:149009916741:android:e1754e20f75b04afa3542c',
    messagingSenderId: '149009916741',
    projectId: 'wefin-calculator',
    storageBucket: 'wefin-calculator.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQtksv_1Pt0d2UdS115dSqtaRLwN06J2k',
    appId: '1:149009916741:ios:16845cdfa15fe65ea3542c',
    messagingSenderId: '149009916741',
    projectId: 'wefin-calculator',
    storageBucket: 'wefin-calculator.firebasestorage.app',
    iosBundleId: 'com.wefin.calculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQtksv_1Pt0d2UdS115dSqtaRLwN06J2k',
    appId: '1:149009916741:ios:62960af299ab428ea3542c',
    messagingSenderId: '149009916741',
    projectId: 'wefin-calculator',
    storageBucket: 'wefin-calculator.firebasestorage.app',
    iosBundleId: 'com.example.weqacalc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYBFy5w8y8FOToPqmtrEP7lh9ecxyI3p8',
    appId: '1:149009916741:web:22b1e45fb8abbf43a3542c',
    messagingSenderId: '149009916741',
    projectId: 'wefin-calculator',
    authDomain: 'wefin-calculator.firebaseapp.com',
    storageBucket: 'wefin-calculator.firebasestorage.app',
    measurementId: 'G-7CBLK4N00K',
  );
}
